channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - autopep8
  - python=3.7
  - tensorboard
  - configargparse
  - pylint
  - cudatoolkit=10.2
  - pytorch=1.7.0
  - tqdm
  - dvc=1.11
  - pip
  - ipython
  - scikit-learn=0.23.2
  - networkx
  - trimesh
  - pyglet
  - pip:
      - torch-geometric
      - gdown
      - ipykernel
      - --find-links https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
      - torch-cluster
      - torch-spline-conv
      - torch-cluster
      - torch-scatter
      - torch-sparse

