channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - pytorch=1.7
  - cudatoolkit=10.2
  - autopep8
  - pylint
  - tensorboard
  - configargparse
  - dvc=1.11
  - tqdm
  - pip:
      - --find-links https://pytorch-geometric.com/whl/torch-1.7.0.html
      - torch-cluster==latest+cu102
      - torch-spline-conv==latest+cu102
      - torch-cluster==latest+cu102
      - torch-scatter==latest+cu102
      - torch-sparse==latest+cu102
  - pip:
      - torch-geometric