channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - python=3.7
  - tensorboard
  - configargparse
  - pylint
  - cudatoolkit=10.2
  - pytorch=1.7
  - tqdm
  - dvc=1.11
  - pip
  - ipython
  - scikit-learn
  - networkx
  - trimesh
  - pyglet
  - pip:
      - torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
      - torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
      - torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
      - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
      - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
