name: Test pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: continuumio/miniconda:4.7.12

    steps:
      - name: Install LFS
        run: |
          apt update
          apt install -y git-lfs
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup environment
        run: conda env update -n base --file ./conda-env.yml
      - name: Test run
        run: conda run -n base dvc repro test_train_model
